lanksi/categories/urls.py
from django.conf.urls import url
from categories import views

urlpatterns = [
    url(r'^$', views.list_, name='list_'),
    url(r'^add$', views.add, name='add'),
    url(r'^view/(?P<slug>[-\w]+)/$', views.details, name="details"),
    url(r'^edit/(?P<slug>[-\w]+)/$', views.edit, name='edit'),
    url(r'^delete/(?P<slug>[-\w]+)/$', views.delete, name='delete'),
    url(r'^confirm-delete/(?P<slug>[-\w]+)$', views.confirm_delete, name='confirm_delete'),
]

lanksi/goals/urls.py
from django.conf.urls import url
from goals import views

urlpatterns = [
    url(r'^$', views.list_, name='list_'),
    url(r'^add$', views.add, name='add'),
    url(r'^add_money/(?P<id>[-\d]+)/$', views.add_money, name='add_money'),
    url(r'^view/(?P<id>[-\d]+)/$', views.details, name="details"),
    url(r'^edit/(?P<id>[-\d]+)/$', views.edit, name='edit'),
    url(r'^delete/(?P<id>[-\d]+)/$', views.delete, name='delete'),
    url(r'^confirm-delete/(?P<id>[-\d]+)$', views.confirm_delete, name='confirm_delete'),
]

lanksi/lanksi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

from accounts import views as bank_views
urlpatterns = [url(r'^i18n/', include('django.conf.urls.i18n')),]

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^register/$', bank_views.register, name='register'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^account/logout/$', auth_views.logout, name='logout'),
    url(r'^categories/', include('categories.urls', namespace='categories')),
    url(r'^goals/', include('goals.urls', namespace='goals')),
    url(r'^patterns/', include('patterns.urls', namespace='patterns')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    url(r'^', bank_views.list_),
    )
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lanksi/categories/models.py
from django.db import models
from django.conf import settings
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class Category(models.Model):
    cat_type = models.SmallIntegerField(choices=settings.TR_TYPES, verbose_name=_('Type'))
    name = models.CharField(max_length=100, verbose_name=_('Name'))
    slug = AutoSlugField(populate_from='name', unique=True, verbose_name=_('Slug'))
    owner = models.ForeignKey(User, verbose_name=_('Owner'))
    created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name=_('Created'))
    updated = models.DateTimeField(auto_now=True, verbose_name=_('Updated'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

lanksi/categories/forms.py
from django import forms
from categories.models import Category
from django.conf import settings


class CategoryForm(forms.ModelForm):
    cat_type = forms.ChoiceField(choices=settings.TR_TYPES, required=False, label='Category type')
    name = forms.CharField(required=False, label='Name')

    class Meta:
        model = Category
        exclude = ('owner', )

lanksi/categories/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required
from categories.models import Category
from categories.forms import CategoryForm

@login_required
def list_(request):
    categories = Category.objects.filter(owner=request.user)
    return render(request, 'categories/list_.html', {'categories': categories})


@login_required
def add(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            new_cat = form.save(commit=False)
            new_cat.owner = request.user
            new_cat.save()
            return redirect(reverse("categories:list_"))
    else:
        form = CategoryForm()
    return render(request, 'categories/add.html', {'form': form})


@login_required
def details(request, slug):
    category = get_object_or_404(Category, slug=slug, owner=request.user)
    return render(request, "categories/details.html", {'category': category})


@login_required
def edit(request, slug):
    category = get_object_or_404(Category, slug=slug, owner=request.user)
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Category.objects.create(cat_type=cd['cat_type'],
                                    name=cd['name'],
                                    owner=request.user)
            category.delete()

            return redirect(reverse("categories:list_"))
    else:
        form = CategoryForm(initial={'cat_type': category.cat_type,
                                         'name': category.name})
    return render(request, "categories/edit.html", {'category': category,
                                                    'form': form})


@login_required
def delete(request, slug):
    category = get_object_or_404(Category, slug=slug, owner=request.user)
    return render(request, 'categories/delete.html', {'category': category})


@login_required
def confirm_delete(request, slug):
    category = get_object_or_404(Category, slug=slug, owner=request.user)
    category.delete()
    return redirect(reverse("categories:list_"))

lanksi/categories/templates/categories/add.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "Add category" %}
{% endblock %}

{% block content %}

    <h2>{% trans "Add category" %}</h2>

    <a href="{% url "categories:list_" %}">{% trans "Go back" %}</a>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans "Save" %}">
    </form>

{% endblock %}

lanksi/categories/templates/categories/delete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "Delete" %} {{ category.name }}?
{% endblock %}

{% block content %}
    <h1>{% trans "Delete" %} {{ category.name }}?</h1>
    <a href="{% url "categories:confirm_delete" category.slug %}">{% trans "Yes" %}</a>
    <a href="{% url "categories:details" category.slug %}">{% trans "No, go back" %}</a>
{% endblock %}

lanksi/categories/templates/categories/details.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h2>{% trans "Category" %}: {{ category.label }}</h2>
<a href="{% url "categories:list_" %}">{% trans "To categories list" %}</a>

<p>{{ category.description }}</p>
<p>{% trans "Category type" %}: {{ category.cat_type }}</p>


<ul>
    <li><a href="{% url "categories:edit" category.slug %}">{% trans "Edit" %}</a></li>
    <li><a href="{% url "categories:delete" category.slug %}">{% trans "Delete" %}</a></li>
</ul>

{% endblock %}

lanksi/categories/templates/categories/edit.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
{% trans "Edit" %} {{ category.name }}
{% endblock %}

{% block content %}

    <h2>{% trans "Edit" %} {{ category.name }}</h2>

    <a href="{% url "categories:details" category.slug %}">{% trans "Go back" %}</a>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans "Save" %}">
    </form>
{% endblock %}

lanksi/categories/templates/categories/list_.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "Hello" %}, {{ request.user }}
{% endblock %}

{% block content %}
    <a href="{% url "categories:add" %}">{% trans "New category" %}</a>
    <p>{% trans "Hello" %}, {{ request.user }}</p>
    {% for category in categories %}
        <ul>
            <li class="category">
                <a href="{% url "categories:details" category.slug %}">{{ category.name }}</a>
                <br>
                {{ category.cat_type }}
                <br>
                {% trans "Created" %} {{ category.created }}
                <br>
                {% trans "Updated" %} {{ category.updated }}
            </li>
        </ul>
    {% endfor %}
{% endblock %}