lanksi/goals/urls.py
from django.conf.urls import url
from goals import views

urlpatterns = [
    url(r'^$', views.list_, name='list_'),
    url(r'^add$', views.add, name='add'),
    url(r'^add_money/(?P<id>[-\d]+)/$', views.add_money, name='add_money'),
    url(r'^view/(?P<id>[-\d]+)/$', views.details, name="details"),
    url(r'^edit/(?P<id>[-\d]+)/$', views.edit, name='edit'),
    url(r'^delete/(?P<id>[-\d]+)/$', views.delete, name='delete'),
    url(r'^confirm-delete/(?P<id>[-\d]+)$', views.confirm_delete, name='confirm_delete'),
]

lanksi/lanksi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

from accounts import views as bank_views
urlpatterns = [url(r'^i18n/', include('django.conf.urls.i18n')),]

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^register/$', bank_views.register, name='register'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^account/logout/$', auth_views.logout, name='logout'),
    url(r'^categories/', include('categories.urls', namespace='categories')),
    url(r'^goals/', include('goals.urls', namespace='goals')),
    url(r'^patterns/', include('patterns.urls', namespace='patterns')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    url(r'^', bank_views.list_),
    )
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lanksi/goals/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from categories.models import Category
from django.utils.translation import ugettext_lazy as _


class Goal(models.Model):
    owner = models.ForeignKey(User, verbose_name=_('Owner'))
    name = models.CharField(max_length=255, verbose_name=_('Name'))
    money_total = models.DecimalField(max_digits=26,
                                      decimal_places=2,
                                      verbose_name=_('Total'))
    money_saved = models.DecimalField(max_digits=26,
                                      decimal_places=2,
                                      default=0,
                                      verbose_name=_('Saved'))
    currency = models.CharField(max_length=3,
                                choices=settings.CURRENCIES,
                                default='RUB',
                                verbose_name=_('Currency'))
    description = models.CharField(blank=True,
                                   null=True,
                                   max_length=255,
                                   verbose_name=_('Description'))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_('Created'))
    updated = models.DateTimeField(auto_now=True, verbose_name=_('Updated'))

    class Meta:
        verbose_name = _('Goal')
        verbose_name_plural = _('Goals')

    def get_money_left(self):
        return self.money_total - self.money_saved

    def add_money(self, amount, acc_from):
        if amount < 0:
            raise Exception('Amount should be > 0')
        elif amount + self.money_saved > self.money_total:
            raise Exception('Too much money to add')
        elif acc_from.balance - amount < 0:
            raise Exception('Not enough money')
        elif acc_from.currency != self.currency:
            raise Exception('Currencies must be the same')
        else:
            if Category.objects.filter(name='Goal: "{}"'.format(self.name)).exists():
                self.money_saved += amount
                acc_from.withdraw_money(amount=amount,
                                        currency=self.currency,
                                        tags='',
                                        category=Category.objects.get(name='Goal: "{}"'.format(self.name)),
                                        comment='')
                self.save()
            else:
                new_cat = Category.objects.create(cat_type=2,
                                                  name='Goal: "{}"'.format(self.name),
                                                  owner=self.owner)
                new_cat.save()
                self.money_saved += amount
                acc_from.withdraw_money(amount=amount,
                                        currency=self.currency,
                                        tags='',
                                        category=Category.objects.get(name='Goal: "{}"'.format(self.name)),
                                        comment='')
                self.save()

lanksi/goals/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from goals.models import Goal
from accounts.models import BankAccount


class GoalForm(forms.ModelForm):
    class Meta:
        model = Goal
        exclude = ('owner', )


class AddMoneyForm(forms.Form):
    class Meta:
        model = Goal

    def __init__(self, *args, **kwargs):
        self.goal = kwargs.pop('goal')
        self.request = kwargs.pop('request')
        super(AddMoneyForm, self).__init__(*args, **kwargs)
        self.fields['acc_from'].queryset = BankAccount.objects.filter(owner=self.request.user)\
                                                              .filter(currency=self.goal.currency)
        self.fields['amount'].max_value = self.goal.get_money_left()

    acc_from = forms.ModelChoiceField(queryset=None, required=True, label=_('Take money from'))
    amount = forms.DecimalField(max_digits=26,
                                decimal_places=2,
                                min_value=0,
                                max_value=None, label=_('Amount'))

lanksi/goals/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required
from goals.models import Goal
from goals.forms import GoalForm, AddMoneyForm


@login_required
def list_(request):
    goals = Goal.objects.filter(owner=request.user)
    return render(request, 'goals/list_.html', {'goals': goals})


@login_required
def add(request):
    if request.method == 'POST':
        form = GoalForm(request.POST)
        if form.is_valid():
            new_cat = form.save(commit=False)
            new_cat.owner = request.user
            new_cat.save()
            return redirect(reverse("goals:list_"))
    else:
        form = GoalForm()
    return render(request, 'goals/add.html', {'form': form})


@login_required
def add_money(request, id):
    goal = get_object_or_404(Goal, id=id, owner=request.user)

    if request.method == 'POST':
        form = AddMoneyForm(request.POST, goal=goal, request=request)
        if form.is_valid():
            cd = form.cleaned_data
            goal.add_money(amount=cd['amount'],
                           acc_from=cd['acc_from'])
            return redirect(reverse("goals:list_"))
    else:
        form = AddMoneyForm(goal=goal, request=request)
    return render(request, 'goals/add_money.html', {'goal': goal,
                                                    'form': form})


@login_required
def details(request, id):
    goal = get_object_or_404(Goal, id=id, owner=request.user)
    return render(request, "goals/details.html", {'goal': goal})


@login_required
def edit(request, id):
    goal = get_object_or_404(Goal, id=id, owner=request.user)
    if request.method == 'POST':
        form = GoalForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Goal.objects.create(owner=request.user,
                                name=cd['name'],
                                money_total=cd['money_total'],
                                money_saved=cd['money_saved'],
                                currency=cd['currency'],
                                description=cd['description'])
            goal.delete()

            return redirect(reverse("goals:list_"))
    else:
        form = GoalForm(initial={'name': goal.name,
                                 'money_total': goal.money_total,
                                 'money_saved': goal.money_saved,
                                 'currency': goal.currency,
                                 'description': goal.description})
    return render(request, "goals/edit.html", {'goal': goal,
                                               'form': form})


@login_required
def delete(request, id):
    goal = get_object_or_404(Goal, id=id, owner=request.user)
    return render(request, 'goals/delete.html', {'goal': goal})


@login_required
def confirm_delete(request, id):
    goal = get_object_or_404(Goal, id=id, owner=request.user)
    goal.delete()
    return redirect(reverse("goals:list_"))

lanksi/goals/templates/goals/add.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

    <h2>{% trans "Add Goal" %}</h2>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans "Save" %}">
    </form>

{% endblock %}

lanksi/goals/templates/goals/add_money.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "Add money to" %} {{ goal.name }}
{% endblock %}

{% block content %}
    <h2>
        {% trans "Add money to" %} {{ goal.name }}
    </h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans "Save" %}">
    </form>
{% endblock %}

lanksi/goals/templates/goals/delete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "Delete" %} {{ goal.name }}?
{% endblock %}

{% block content %}
    <h1>{% trans "Delete" %} {{ goal.name }}?</h1>
    <a href="{% url "goals:confirm_delete" goal.id %}">{% trans "Yes" %}</a>
    <a href="{% url "goals:details" goal.id %}">{% trans "No, go back" %}</a>
{% endblock %}

lanksi/goals/templates/goals/details.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h2>{% trans "Goal" %}: {{ goal.name }}</h2>
<a href="{% url "goals:list_" %}">{% trans "Go to goals list" %}</a>
<br><br>
<strong>{% trans "Remained to save up" %}: {{ goal.get_money_left }}</strong>

<p>{{ goal.description }}<p>

<ul>
    <li><a href="{% url "goals:edit" goal.id %}">{% trans "Edit goal" %}</a></li>
    <li><a href="{% url "goals:delete" goal.id %}">{% trans "Delete goal" %}</a></li>
</ul>

{% endblock %}

lanksi/goals/templates/goals/edit.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "Edit" %} {{ goal.name }}
{% endblock %}

{% block content %}
    <a href="{% url "goals:details" goal.id %}">{% trans "Go back" %}</a>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans "Save" %}">
    </form>
{% endblock %}

lanksi/goals/templates/goals/list_.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "Hello" %}, {{ request.user }}
{% endblock %}

{% block content %}
    <a href="{% url "goals:add" %}">{% trans "New Goal" %}</a>
    <p>Hello, {{ request.user }}</p>
    {% for goal in goals %}
        <ul>
            <li class="goal">
                <a href="{% url "goals:details" goal.id %}">{{ goal.name }}</a>
                <br>
                {% trans "Saved up so far" %}: {{ goal.money_saved }} {{ goal.currency }}
                <br>
                {% trans "Remained to save up" %}: {{ goal.get_money_left }} {{ goal.currency }}
                <a href="{% url "goals:add_money" goal.id %}">{% trans "Add money" %}</a>
                <br>
                {% trans "Created" %} {{ goal.created }}
                <br>
                {% trans "Updated" %} {{ goal.updated }}
            </li>
        </ul>
    {% endfor %}
{% endblock %}