lanksi/accounts/urls.py
from django.conf.urls import url
from accounts import views

urlpatterns = [
    url(r'^operation/add/(?P<slug>[-\w]+)$',          views.add_money,           name="add_money"),
    url(r'^operation/withdraw/(?P<slug>[-\w]+)$',     views.withdraw_money,      name="withdraw_money"),
    url(r'^operation/move/(?P<slug>[-\w]+)$',         views.move_money,          name="move_money"),
    url(r'^operation/exchange/(?P<slug>[-\w]+)$',     views.exchange_money,      name='exchange_money'),

    url(r'^$', views.list_, name='list_'),
    url(r'^add$', views.add, name='add'),
    url(r'^edit/(?P<slug>[-\w]+)/$', views.edit, name='edit'),
    url(r'^delete/(?P<slug>[-\w]+)/$', views.delete, name='delete'),
    url(r'^confirm-delete/(?P<slug>[-\w]+)$', views.confirm_delete, name='confirm_delete'),
    url(r'^credentials/$', views.manage_credentials, name='manage_credentials'),
]

lanksi/goals/urls.py
from django.conf.urls import url
from goals import views

urlpatterns = [
    url(r'^$', views.list_, name='list_'),
    url(r'^add$', views.add, name='add'),
    url(r'^add_money/(?P<id>[-\d]+)/$', views.add_money, name='add_money'),
    url(r'^view/(?P<id>[-\d]+)/$', views.details, name="details"),
    url(r'^edit/(?P<id>[-\d]+)/$', views.edit, name='edit'),
    url(r'^delete/(?P<id>[-\d]+)/$', views.delete, name='delete'),
    url(r'^confirm-delete/(?P<id>[-\d]+)$', views.confirm_delete, name='confirm_delete'),
]

lanksi/lanksi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

from accounts import views as bank_views
urlpatterns = [url(r'^i18n/', include('django.conf.urls.i18n')),]

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^register/$', bank_views.register, name='register'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^account/logout/$', auth_views.logout, name='logout'),
    url(r'^categories/', include('categories.urls', namespace='categories')),
    url(r'^goals/', include('goals.urls', namespace='goals')),
    url(r'^patterns/', include('patterns.urls', namespace='patterns')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    url(r'^', bank_views.list_),
    )
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lanksi/accounts/views.py
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.core.serializers import get_serializer
from django.views.generic import FormView
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from accounts.mixins import AjaxFormMixin
from accounts.models import BankAccount, Transaction, ExchangeRate
from accounts.forms import (TransactionForm,
                            MoveMoneyForm,
                            FilterHistoryForm,
                            AddBankAccountForm,
                            EditBankAccountForm,
                            ExchangeForm,
                            ExportDataForm,
                            ImportDataForm)
from patterns.models import TransactionTemplate


def get_sums(spis):
    gena = []
    new_gena = []
    for each in spis:
        entry = {'currency': each['currency'], 'values': [each['balance']]}
        if each['currency'] not in [i.get('currency') for i in gena]:
            gena.append(entry)
        else:
            for j, _ in enumerate(gena):
                if each['currency'] == gena[j]['currency']:
                    gena[j]['values'].append(each['balance'])
    for each in gena:
        new_gena.append({'currency': each['currency'], 'value': str(sum(each['values']))})
    return new_gena


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse('login'))
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


#region accounts
def get_history(queryset):
    history_items = []
    for t in queryset:
        item = {'transaction_id': t.id, 'type': None, 'description': t.comment, 'datetime': t.created, 'category': _('No category'),
                'amount': t.tr_amount, 'currency': t.currency, 'from': '', 'to': ''}
        if t.category:
            item['category'] = t.category
        if t.tr_type == settings.TR_ADD:
            item['type'] = 1
            item['to'] = t.tr_from
        elif t.tr_type == settings.TR_WITHDRAW:
            item['type'] = 2
            item['from'] = t.tr_from
        elif t.tr_type == settings.TR_MOVE:
            item['type'] = 3
            item['from'] = t.tr_from
            item['to'] = t.tr_to
        elif t.tr_type == settings.TR_EXCHANGE:
            item['type'] = 4
            item['from'] = t.tr_from
            item['to'] = t.tr_to


        history_items.append(item)

    return history_items


def save_accounts_data():
    JSONseriaizer = get_serializer('json')
    json_seriaizer = JSONseriaizer()
    with open("file.json", "w") as out:
        json_seriaizer.serialize(BankAccount.objects.all(), indent=4, stream=out)


@login_required
def manage_credentials(request):
    export_form = ExportDataForm()
    import_form = ImportDataForm()
    return render(request, 'manage_credentials.html', {'export_form': export_form,
                                                       'import_form': import_form})


@login_required
def list_(request):
    accounts = BankAccount.objects.filter(owner=request.user)
    patterns = TransactionTemplate.objects.filter(owner=request.user)
    from django.db.models import Q
    queryset = Transaction.objects.filter(
        Q(tr_from__in=accounts) | Q(tr_to__in=accounts)).order_by('-created')

    if request.method == 'POST':
        form = FilterHistoryForm(request.POST, request=request)
        if form.is_valid():
            if form.cleaned_data['time_period']:
                queryset = queryset.filter(created__gte=form.cleaned_data['time_period'])
            if form.cleaned_data['date_from']:
                queryset = queryset.filter(created__gte=form.cleaned_data['date_from'])
            if form.cleaned_data['date_to']:
                queryset = queryset.filter(created__lte=form.cleaned_data['date_to'])
            if form.cleaned_data['keywords']:
                queryset = queryset.filter(comment__contains=form.cleaned_data['keywords'])
            if form.cleaned_data['account']:
                queryset = queryset.filter(Q(tr_from=form.cleaned_data['account']))
            if form.cleaned_data['category']:
                queryset = queryset.filter(category=form.cleaned_data['category'])
    else:
        form = FilterHistoryForm(request=request)

    history_items = get_history(queryset=queryset)
    return render(request, 'accounts/list_.html', {'accounts': accounts,
                                                   'patterns': patterns,
                                                   'form': form,
                                                   'history': history_items})


@login_required
def add(request):
    if request.method == 'POST':
        form = AddBankAccountForm(request.POST)
        if form.is_valid():
            new_acc = form.save(commit=False)
            new_acc.owner = request.user
            new_acc.save()
            return redirect(reverse("accounts:list_"))
    else:
        form = AddBankAccountForm()
    return render(request, 'accounts/add.html', {'form': form})

@login_required
def edit(request, slug):
    account = BankAccount.objects.get(slug=slug, owner=request.user)
    if request.method == 'POST':
        form = EditBankAccountForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            BankAccount.objects.create(label=cd['label'],
                                       currency=account.currency,
                                       balance=account.balance,
                                       owner=request.user,
                                       description=cd['description'])
            account.delete()

            return redirect(reverse("accounts:list_"))
    else:
        form = EditBankAccountForm(initial={'label': account.label,
                                            'description': account.description})
    return render(request, "accounts/edit.html", {'account': account,
                                                  'form': form})


@login_required
def delete(request, slug):
    account = BankAccount.objects.get(slug=slug, owner=request.user)
    return render(request, 'accounts/delete.html', {'account': account})


@login_required
def confirm_delete(request, slug):
    account = BankAccount.objects.get(slug=slug, owner=request.user)
    account.delete()
    return redirect(reverse("accounts:list_"))
#endregion accounts


#region operations

# class AddMoneyView(AjaxFormMixin, FormView):
#     form_class = TransactionForm
#     template_name = "accounts/money_transfer.html"
#     success_url = "/accounts/"
#
#     def dispatch(self, request, *args, **kwargs):
#         self.slug = kwargs.get('slug', None)
#         self.user = kwargs.get('request', None)
#
#     def get_context_data(self, **kwargs):
#         context = super(AddMoneyView, self).get_context_data(**kwargs)
#         context['account'] = BankAccount.objects.get(slug=self.slug, owner=self.request.user)
#         return context

@login_required
def add_money(request, slug):
    account = get_object_or_404(BankAccount, slug=slug, owner=request.user)
    if request.method == 'POST':
        form = TransactionForm(request.POST, request=request, cat_type=settings.TR_ADD)
        if form.is_valid():
            cd = form.cleaned_data
            account.add_money(amount=cd['amount'],
                              currency=account.currency,
                              tags=cd['tr_tags'],
                              category=cd['category'],
                              comment=cd['comment'])
            return redirect(reverse("accounts:list_"))
    else:
        form = TransactionForm(request=request, cat_type=settings.TR_ADD)
    return render(request, "accounts/money_transfer.html", {'account': account,
                                                            'form': form,
                                                            'msg': _('Add money to "{}"'.format(account.label))})


@login_required
def withdraw_money(request, slug):
    account = get_object_or_404(BankAccount, slug=slug, owner=request.user)
    if request.method == 'POST':
        form = TransactionForm(request.POST, request=request, cat_type=settings.TR_WITHDRAW)
        if form.is_valid():
            cd = form.cleaned_data
            account.withdraw_money(amount=cd['amount'],
                                   currency=account.currency,
                                   tags=cd['tr_tags'],
                                   category=cd['category'],
                                   comment=cd['comment'])
            return redirect(reverse("accounts:list_"))
    else:
        form = TransactionForm(request=request, cat_type=settings.TR_WITHDRAW)
    return render(request, "accounts/money_transfer.html", {'account': account,
                                                            'form': form,
                                                            'msg': _('Withdraw money from "{}"'.format(account.label))})


@login_required
def move_money(request, slug):
    account = get_object_or_404(BankAccount, slug=slug, owner=request.user)
    if request.method == 'POST':
        form = MoveMoneyForm(request.POST,
                             request=request,
                             account=account,
                             cat_type=settings.TR_MOVE)
        if form.is_valid():
            cd = form.cleaned_data
            account.move_money(to_account=cd['account'],
                               amount=cd['amount'],
                               currency=account.currency,
                               tags=cd['tr_tags'],

lanksi/accounts/templates/accounts/add.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

    <h2>{% trans "Add Account" %}</h2>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans "Save" %}">
    </form>

{% endblock %}

lanksi/accounts/templates/accounts/delete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "Delete" %} {{ account.label }}?
{% endblock %}

{% block content %}
    <h1>Delete {{ account.label }}?</h1>
    <a href="{% url "accounts:confirm_delete" account.slug %}">{% trans "Yes" %}</a>
    <a href="{% url "accounts:list_" %}">{% trans "No, go back" %}</a>
{% endblock %}

lanksi/accounts/templates/accounts/edit.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "Edit" %} {{ account.label }}
{% endblock %}

{% block content %}
    <a href="{% url "accounts:list_" %}">{% trans "Go back" %}</a>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans "Save" %}">
    </form>
{% endblock %}

lanksi/accounts/templates/accounts/list_.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
{% trans "Hello" %}, {{ request.user }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-3 border">
                <p class="text-center">{% trans "Hello" %}, {{ request.user }}</p>

                <button data-toggle="collapse" data-target="#accounts" class="btn btn-sm btn-dark">
                    {% trans "Accounts" %}
                </button>
                <button data-toggle="collapse" data-target="#patterns" class="btn btn-sm btn-dark">
                    {% trans "Patterns" %}
                </button>


                <div id="accounts" class="collapse in">

                    <div class="text-center">
                        <a href="{% url "accounts:add" %}" class="btn btn-sm btn-info btn-center">
                            {% trans "Create new account" %}
                        </a>
                    </div>

                    {% for account in accounts %}
                    <div class="container border border-info account">
                    <div>
                        <p>{{ account.label }}</p>
                        <br>
                        {{ account.balance }} {{ account.currency }}
                        <br>
                        {% trans "Created" %} {{ account.creation_date }}
                    </div>

                        <a href="{% url "accounts:edit" account.slug %}">
                            <img src="{% static 'accounts/img/edit.png' %}" title="{% trans "Edit account" %}">
                        </a>

                        <a href="{% url "accounts:delete" account.slug %}">
                            <img src="{% static 'accounts/img/delete.png' %}" title="{% trans "Delete account" %}">
                        </a>

                        <a href="{% url "accounts:add_money" account.slug %}">
                            <img src="{% static 'accounts/img/plus.png' %}" title="{% trans "Add money" %}">
                        </a>

                        <a href="{% url "accounts:withdraw_money" account.slug %}">
                            <img src="{% static 'accounts/img/minus.png' %}" title="{% trans "Withdraw money" %}">
                        </a>

                        <a href="{% url "accounts:move_money" account.slug %}">
                            <img src="{% static 'accounts/img/move.png' %}" title="{% trans "Transfer money" %}">
                        </a>

                        <a href="{% url "accounts:exchange_money" account.slug %}">
                            <img src="{% static 'accounts/img/exchange.png' %}" title="{% trans "Exchange money" %}">
                        </a>
                    </div>
            {% endfor %}
                </div>
                <div id="patterns" class="collapse">
                    <div class="text-center">
                        <a href="{% url "patterns:add" %}" class="btn btn-sm btn-info btn-center">
                            {% trans "Create new pattern" %}
                        </a>
                    </div>

                    {% for pattern in patterns %}
                    <div class="container border border-info account">
                    <div>
                        <p>{{ pattern.name }}</p>
                        <br>
                        {{ pattern.description }}
                        <br>
                        {{ pattern.transaction }}
                        <br>
                        <br>
                        <br>
                        {% trans "Created" %} {{ pattern.created }}
                        {% trans "Updated" %} {{ pattern.updated }}
                    </div>

                        <a href="{% url "patterns:edit" pattern.id %}">
                            <img src="{% static 'accounts/img/edit.png' %}" title="{% trans "Edit pattern" %}">
                        </a>

                        <a href="{% url "patterns:delete" pattern.id %}">
                            <img src="{% static 'accounts/img/delete.png' %}" title="{% trans "Delete pattern" %}">
                        </a>
                    </div>
            {% endfor %}
                </div>
            </div>
            <div class="col-sm-9">
                <h2>{% trans "History" %}</h2>
                <a href="#filter" data-toggle="collapse">{% trans "Filter" %}:</a>
                <div id="filter" class="collapse history-filter">

                    <form class="form-inline" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>{% trans "Category" %}:</label>
                            {{ form.category }}
                        </div>
                        <div class="form-group">
                            <label>{% trans "Account" %}:</label>
                            {{ form.account }}
                         </div>
                        <div class="form-group">
                            <label>{% trans "Time period" %}:</label>
                            {{ form.time_period }}
                        </div>
                        <div class="form-group">
                            <label>{% trans "From" %}:</label>
                            {{ form.date_from }}
                        </div>
                        <div class="form-group">
                            <label>{% trans "To" %}:</label>
                            {{ form.date_to }}
                        </div>
                        <div class="form-group">
                            <label>{% trans "Keywords" %}:</label>
                            {{ form.keywords }}
                        </div>

                    <input type="submit" value="{% trans "Apply" %}">
                </form>
                </div>

                {% for item in history %}
                    <div class="history-item border border-info">
                        <div class="history history-type">
                            {% if item.type == 1 %}
                                <img src="{% static 'accounts/img/plus.png' %}" class="history-type">
                            {% elif item.type == 2 %}
                                <img src="{% static 'accounts/img/minus.png' %}" class="history-type">
                            {% elif item.type == 3 %}
                                <img src="{% static 'accounts/img/move.png' %}" class="history-type">
                            {% elif item.type == 4 %}
                                <img src="{% static 'accounts/img/exchange.png' %}" class="history-type">
                            {% endif%}
                        </div>
                        <div class="history history-category">
                            {% trans "Category" %}: {{ item.category }}
                        </div>
                        <div class="history history-amount">
                            {% trans "Amount" %}: {{ item.amount }} {{ item.currency }}
                        </div>
                        <div class="history history-date">
                            {% trans "Date" %}: {{ item.datetime }}
                        </div>
                        <div class="history history-desc">
                            {% trans "Comment" %}: {{ item.description }}
                        </div>
                        <div class="history history-from">
                            {% trans "From" %}: {{ item.from }}
                        </div>
                        <div class="history history-to">
                            {% trans "To" %}: {{ item.to }}
                        </div>
                        <div class="history history-save-pattern">
                            <a href="{% url "patterns:add" %}?trans_id={{ item.transaction_id }}">
                                <img src="{% static "accounts/img/save.png" %}" title="{% trans "Save as template" %}">
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

lanksi/accounts/templates/accounts/money_transfer.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h2>{{ msg }}</h2>

<a href="{% url "accounts:list_" %}">{% trans "Go back" %}</a>
<form method="POST">
    {% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="{% trans "Save" %}">

    <script>
        function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
        }

        var csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
    </script>
</form>

{% endblock %}

{% block domready %}

    function(event){
        event.preventDefault()
        var $formData = $(this).serialize()
        var $thisURL = $myForm.attr('data-url') || window.location.href // or set your own url
        $.ajax({
            method: "POST",
            url: $thisURL,
            data: $formData,
            success: handleFormSuccess,
            error: handleFormError,
        })
    })

    function handleFormSuccess(data, textStatus, jqXHR){
        console.log(data)
        console.log(textStatus)
        console.log(jqXHR)
        $myForm.reset(); // reset form data
    }

    function handleFormError(jqXHR, textStatus, errorThrown){
        console.log(jqXHR)
        console.log(textStatus)
        console.log(errorThrown)
    }
{% endblock %}