lanksi/goals/urls.py
from django.conf.urls import url
from goals import views

urlpatterns = [
    url(r'^$', views.list_, name='list_'),
    url(r'^add$', views.add, name='add'),
    url(r'^add_money/(?P<id>[-\d]+)/$', views.add_money, name='add_money'),
    url(r'^view/(?P<id>[-\d]+)/$', views.details, name="details"),
    url(r'^edit/(?P<id>[-\d]+)/$', views.edit, name='edit'),
    url(r'^delete/(?P<id>[-\d]+)/$', views.delete, name='delete'),
    url(r'^confirm-delete/(?P<id>[-\d]+)$', views.confirm_delete, name='confirm_delete'),
]

lanksi/lanksi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

from accounts import views as bank_views
urlpatterns = [url(r'^i18n/', include('django.conf.urls.i18n')),]

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^register/$', bank_views.register, name='register'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^account/logout/$', auth_views.logout, name='logout'),
    url(r'^categories/', include('categories.urls', namespace='categories')),
    url(r'^goals/', include('goals.urls', namespace='goals')),
    url(r'^patterns/', include('patterns.urls', namespace='patterns')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    url(r'^', bank_views.list_),
    )
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lanksi/templates/base.html
{% load staticfiles %}
{% load i18n %}
{% load get_percent %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Welcome to Lanksi{% endblock %}</title>
        <link href="{% static "accounts/css/main.css" %}" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    </head>
    <body>
        <div id="header">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand" href="{% url "accounts:list_" %}">Lanksi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url "accounts:list_" %}">{% trans "Accounts" %} <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url "categories:list_" %}">{% trans "Categories" %}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url "goals:list_" %}">{% trans "Goals" %}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url "patterns:list_" %}">{% trans "Patterns" %}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " href="#">
                                    {% trans "Import & export credentials" %}
                                </a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            {% ifequal LANGUAGE_CODE "en"  %}
                            <a href="/ru{{ request.get_full_path|slice:'3:' }}">
                                <img src="{% static 'accounts/img/russian.gif' %}">
                            </a>
                            {% else %}
                                <a href="/en{{ request.get_full_path|slice:'3:' }}">
                                    <img src="{% static 'accounts/img/english.gif' %}">
                                </a>
                            {% endifequal %}
                        </li>

                        {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url "logout" %}">{% trans "Logout" %}</a>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url "login" %}">{% trans "Login" %}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url "register" %}">{% trans "Register" %}</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
        <div class="row">
            <div class="col-sm-9">
              {% block content %}
              {% endblock %}
            </div>
            <div class="col-sm-3">
                {% block content-right %}

                    <button data-toggle="collapse" data-target="#rates" class="btn btn-sm btn-dark">
                        {% trans "Exchange rates" %}
                    </button>
                    <button data-toggle="collapse" data-target="#summary" class="btn btn-sm btn-dark">
                        {% trans "Summary" %}
                    </button>
                    <button data-toggle="collapse" data-target="#goals" class="btn btn-sm btn-dark">
                        {% trans "Goals" %}
                    </button>
                    <div id="rates" class="collapse border border-info">
                        <p class="text-center">{% trans "Exchange rates:" %}</p>
                        <ul class="list-group">
                            {% for rate in rates %}
                                <li class="list-group-item">
                                    <p class="text-center">
                                        {{ rate }}
                                        <br>
                                        {{ rate.value }}
                                    </p>
                                </li>
                            {% endfor %}
                        </ul>
                        <p class="text-center">
                            {% trans "Last updated:" %}
                            <br>
                            {{ rates.0.date }}
                        </p>
                    </div>

                    <div id="summary" class="collapse border border-info">
                        <p class="text-center">{% trans "Summary table of account balances:" %}</p>
                        {% for account in accounts %}
                            <div class="account">
                                {{ account.label }}
                                <br>
                                {{ account.balance }} {{ account.currency }}
                            </div>
                        {% endfor %}

                        {% trans "Total:" %}
                        <ul class="list-group">
                        {% for sum in sums %}
                            <li class="list-group-item">
                                {{ sum.value }} {{ sum.currency }}
                            </li>
                        {% endfor %}
                        </ul>
                    </div>

                    <div id="goals" class="collapse border border-info">
                        <div class="text-center">
                            <a href="{% url "goals:add" %}" class="btn btn-info"></a>
                        </div>
                        <p class="text-center">{% trans "Your goals" %}:</p>
                        {% for goal in goals %}
                            <div class="goal border border-info">
                                {{ goal.name }}
                                <br>
                                <br>
                                {% trans "Total" %}:
                                <br>
                                {{ goal.money_total }}
                                <br>
                                <br>
                                {% trans "Saved up so far" %}:
                                <br>
                                {{ goal.money_saved }}
                                <br>
                                <div class="progress">
                                    <div class="progress-bar progress-bar-success progress-bar-striped"
                                         role="progressbar"
                                         aria-valuenow="{{ goal.money_saved|get_percent:goal.money_total }}"
                                         aria-valuemin="0"
                                         aria-valuemax="100"
                                         style="width:{{ goal.money_saved|get_percent:goal.money_total }}%">
                                        <span>{{ goal.money_saved|get_percent:goal.money_total }}% {% trans "Complete" %}</span>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    </div>

                {% endblock %}
                </div>
            </div>


        <script src="https://code.jquery.com/jquery-3.2.1.min.js" ></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.js"></script>
{#        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>#}
        <script>
            $(document).ready(
            {% block domready %}

            {% endblock %}
            )
        </script>
    </body>
</html>

lanksi/templates/manage_credentials.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "Import & Export" %}
{% endblock %}

{% block content %}
    <h2>{% trans "Import & Export" %}</h2>
    <p>{% trans "Import & Export your accounts data, goals, categories etc" %}</p>
    <div class="export">
        <p>Export:</p>

    </div>
    <div class="import">
    <p>Import:</p>
    <form method="post">
        {% csrf_token %}
        {{ import_form.as_p }}
    </form>
    </div>
{% endblock %}